scripts/deployment/globals_gnosis_mainnet.json
- Everest service staking contract address.
=> chore: everest service staking contract address

scripts/deployment/globals_gnosis_mainnet.json
- Updating staking param values.
=> chore: updating staking param values

.gitmodules, contracts/test/ABICreator.sol, contracts/test/ERC20Token.sol, contracts/test/MockAgentMech.sol, contracts/test/SafeNonceLib.sol, scripts/deployment/deploy_00_basic_service_staking_activity_checker.js
- Tagging registries, updating solidity version in test contracts.
=> chore: tagging registries, updating solidity version in test contracts

scripts/deployment/globals_base_mainnet_contribute.json, scripts/deployment/globals_base_mainnet_contribute_alpha2.json, scripts/deployment/globals_base_mainnet_contribute_alpha3.json
- Adding more staking contracts.
=> chore: adding more staking contracts

scripts/deployment/deploy_11_contributors_proxy_change_manager.js, scripts/deployment/deploy_12_contributors_proxy_set_contribute_agent_statuses.js, scripts/deployment/deploy_13_contributors_proxy_change_owner.js, scripts/deployment/globals_base_mainnet_contribute.json, scripts/deployment/globals_base_mainnet_contribute_alpha.json, scripts/deployment/globals_base_mainnet_contribute_alpha2.json, scripts/deployment/globals_base_mainnet_contribute_alpha3.json
=> chore: deployment of contributes

scripts/deployment/globals_base_mainnet_contribute_alpha.json, scripts/deployment/globals_base_mainnet_contribute_alpha2.json, scripts/deployment/globals_base_mainnet_contribute_alpha3.json, scripts/deployment/globals_mode_mainnet_optimus_alpha.json
=> chore: udpating configs

scripts/deployment/globals_base_mainnet_contribute_alpha.json, scripts/deployment/globals_base_mainnet_contribute_alpha2.json, scripts/deployment/globals_base_mainnet_contribute_alpha3.json, scripts/deployment/globals_gnosis_mainnet_pearl_beta3.json, scripts/deployment/globals_gnosis_mainnet_pearl_beta5.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_expert6.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_expert7.json, scripts/deployment/globals_mode_mainnet_optimus_alpha.json
=> chore: updating staking configs

scripts/deployment/globals_gnosis_mainnet_pearl_beta6.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_expert17.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_expert18.json, scripts/deployment/globals_mode_mainnet_modius_alpha.json, scripts/deployment/globals_mode_mainnet_modius_alpha2.json, scripts/deployment/globals_mode_mainnet_modius_alpha3.json, scripts/deployment/globals_mode_mainnet_modius_alpha4.json
- Updated deployed staking setups.
=> chore: updated deployed staking setups

scripts/deployment/globals_base_mainnet_contribute.json, scripts/deployment/globals_base_mainnet_contribute_beta.json, scripts/deployment/globals_base_mainnet_contribute_beta2.json, scripts/deployment/globals_base_mainnet_contribute_beta3.json
=> chore: contribute 0.2 deployment

scripts/deployment/globals_base_mainnet_contribute.json
=> chore: recoverer address

contracts/dual_token/DualStakingToken.sol, contracts/dual_token/DualStakingTokenActivityChecker.sol, contracts/dual_token/interfaces/IStaking.sol
- Accounting for initial version findings.
=> refactor: accounting for initial version findings

audits/README.md, audits/internal3/README.md
- Internal audit folder: contracts/dual_token
=> doc: internal audit

contracts/dual_token/DualStakingToken.sol, contracts/dual_token/DualStakingTokenActivityChecker.sol, contracts/dual_token/interfaces/IService.sol, contracts/dual_token/interfaces/IStaking.sol, contracts/libraries/SafeTransferLib.sol
- Initial dual staking token approach implementation.
=> feat: dual staking token

audits/README.md, audits/internal3/README.md, contracts/dual_token/DualStakingToken.sol, contracts/dual_token/DualStakingTokenActivityChecker.sol, contracts/dual_token/interfaces/IStaking.sol, test/StakingDualToken.js
- Making dual token is onwerless;
- Naming correction;
- Natspec;
- Testing.
=> refactor: dual token is onwerless, naming correction

scripts/audit_staking_setups/audit_setup.js, scripts/deployment/globals_base_mainnet_fun_alpha.json, scripts/deployment/globals_base_mainnet_fun_alpha2.json, scripts/deployment/globals_base_mainnet_fun_alpha3.json, scripts/deployment/globals_base_mainnet_mech_marketplace_alpha.json, scripts/deployment/globals_base_mainnet_requester_marketplace_alpha.json, scripts/deployment/globals_base_mainnet_requester_marketplace_alpha2.json, scripts/deployment/globals_gnosis_mainnet_mech_marketplace_alpha.json, scripts/deployment/globals_gnosis_mainnet_requester_marketplace_alpha.json, scripts/deployment/globals_gnosis_mainnet_requester_marketplace_alpha2.json
- Updating deployed contract configs.
=> chore: updating deployed contract configs

contracts/dual_token/DualStakingToken.sol, test/StakingDualToken.js
- Adding fallback for staking staticcall.
=> refactor: adding fallback for staking staticcall

scripts/audit_staking_setups/audit_setup.js, scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace3.json, scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace4.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert3.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert4.json, scripts/deployment/globals_mode_mainnet_modius_alpha5.json, scripts/deployment/globals_mode_mainnet_modius_alpha6.json, scripts/deployment/globals_mode_mainnet_optimus_alpha2.json, scripts/deployment/globals_mode_mainnet_optimus_alpha3.json, scripts/deployment/globals_optimistic_mainnet_optimus_alpha2.json, scripts/deployment/globals_optimistic_mainnet_optimus_alpha3.json, scripts/deployment/globals_optimistic_mainnet_optimus_alpha4.json
=> chore: updating staking setups

scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace3.json, scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace4.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert3.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert4.json
- Updating staking contracts configurations
=> chore: updating staking contracts configurations

scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace3.json, scripts/deployment/globals_gnosis_mainnet_pearl_beta_new_marketplace4.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert3.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert4.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert5.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert6.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert7.json, scripts/deployment/globals_gnosis_mainnet_qs_beta_new_marketplace_expert8.json
- Deployment of new staking contracts
=> chore: deployment of staking contracts

audits/README.md, audits/internal5/README.md
- Internal audit.
- No issue, notes for discussion and improve hash calculation
=> doc: internal audit 5

CHANGELOG.md
=> doc: adding changelog
